language: bash

before_script:
  - sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu utopic main universe"
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

script:
  - shellcheck src/lib/shell.sh
  - shellcheck src/lib/helpers.sh

notifications:
  email: false
